
DROP DATABASE IF EXISTS burgers2_db;

CREATE DATABASE burgers2_db;
USE burgers2_db;

-- USE burgers_db;

-- CREATE TABLE burgers 
-- (
-- 	id INT NOT NULL AUTO_INCREMENT,
-- 	burger_name VARCHAR(255) NOT NULL,
-- 	devoured BOOLEAN DEFAULT FALSE,
-- 	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   	dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
-- 	PRIMARY KEY (id)
-- );

-- SELECT * FROM burgers;





