-- INSERT INTO burgers (burger_name, devoured) VALUES ('whataburger', false);
-- INSERT INTO burgers (burger_name, devoured) VALUES ('fatburger', false);
-- INSERT INTO burgers (burger_name, devoured) VALUES ('steakburger', false);